// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Yggdrasil.Imports.Api.Infrastructure.Context;

#nullable disable

namespace Yggdrasil.Imports.Api.Infrastructure.Migrations
{
    [DbContext(typeof(ImportsApiContext))]
    [Migration("20230503033131_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Yggdrasil.Imports.Domain.Entities.CrsImportEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ImportDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ImportStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CrsImports");
                });
#pragma warning restore 612, 618
        }
    }
}
